/**
 * Evidence safety scanner. The manifest writer refuses (throws) instead of "cleaning":
 * a refused write means a tool tried to record something it must never record, which is
 * a bug to fix at the source, not to mask.
 *
 * Never recorded: credentials, authorization headers, cookies, raw IP identities,
 * request bodies / user data, DB URLs with passwords, private keys, JWTs.
 */

const FORBIDDEN_KEY_FRAGMENTS = [
  "authorization", "cookie", "password", "passwd", "secret", "apikey", "credential", "privatekey",
  "token", "bearer", "body", "payload", "forwarded", "clientip", "remoteaddr", "remoteaddress",
  "connectionstring", "databaseurl", "dsn", "email",
] as const;

/** Keys that are exactly an IP-identity carrier regardless of value. */
const FORBIDDEN_EXACT_KEYS = new Set(["ip", "ips", "address", "addresses", "headers", "header", "host", "hostname", "origin", "url", "uri"]);

const VALUE_PATTERNS: readonly [string, RegExp][] = [
  ["bearer-credential", /\bBearer\s+[A-Za-z0-9._~+/=-]{6,}/i],
  ["basic-credential", /\bBasic\s+[A-Za-z0-9+/=]{8,}/],
  ["url-with-credentials", /[a-z][a-z0-9+.-]*:\/\/[^\s/:@]+:[^\s/@]+@/i],
  ["jwt", /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]*/],
  ["private-key", /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
  ["aws-access-key", /\bAKIA[0-9A-Z]{16}\b/],
  ["provider-api-key", /\b(re_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,}|AIza[0-9A-Za-z_-]{30,}|ghp_[A-Za-z0-9]{30,})\b/],
  ["cookie-header-value", /(^|[;\s])(session|sid|csrf|__Host-[A-Za-z-]+|__Secure-[A-Za-z-]+)=[^;\s]{6,}/i],
  ["email-address", /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/],
];

const IPV4 = /(?<![\d.])(?:(?:25[0-5]|2[0-4]\d|1?\d?\d)\.){3}(?:25[0-5]|2[0-4]\d|1?\d?\d)(?![\d]|\.\d)/;
const IPV6 = /(?<![0-9A-Fa-f:])(?:[0-9A-Fa-f]{0,4}:){2,7}[0-9A-Fa-f]{0,4}(?![0-9A-Fa-f:])/;

export class EvidenceViolation extends Error {
  constructor(readonly path: string, readonly rule: string) {
    super(`evidence refused at ${path}: ${rule}`);
    this.name = "EvidenceViolation";
  }
}

function normalizeKey(key: string): string {
  return key.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function scanString(path: string, key: string, value: string, relaxedVersionField: boolean): void {
  if (value.length > 512) throw new EvidenceViolation(path, "string longer than 512 characters");
  for (const [rule, pattern] of VALUE_PATTERNS) if (pattern.test(value)) throw new EvidenceViolation(path, rule);
  if (!relaxedVersionField) {
    if (IPV4.test(value)) throw new EvidenceViolation(path, "raw IPv4 address");
    if (IPV6.test(value) && !/^\d{1,2}:\d{2}(:\d{2})?/.test(value) && !/^\d{4}-\d{2}-\d{2}T/.test(value)) throw new EvidenceViolation(path, "raw IPv6 address");
  }
  const normalized = normalizeKey(key);
  if (/^[0-9a-f]{64}$/.test(value) && !normalized.endsWith("sha256")) throw new EvidenceViolation(path, "64-hex value outside a sha256 field (possible secret)");
  if (/^[0-9a-f]{40}$/.test(value) && normalized !== "gitsha") throw new EvidenceViolation(path, "40-hex value outside gitSha");
  // Run ids are generated by EvidenceRun (timestamp-label-random) and are the one long identifier we emit.
  if (/^[A-Za-z0-9_+/=-]{32,}$/.test(value) && !/^[0-9a-f]{40,64}$/.test(value) && normalized !== "runid") throw new EvidenceViolation(path, "long token-like string");
}

/**
 * Walks a JSON-like value. `environment` (collector-built) may contain dotted version strings that
 * look like IPv4 (e.g. a kernel release), so IP detection is relaxed there only; every other rule applies.
 */
export function assertEvidenceSafe(value: unknown, path = "$", relaxedVersionField = false): void {
  if (value === null || typeof value === "number" || typeof value === "boolean") return;
  if (typeof value === "string") { scanString(path, path.split(".").pop() ?? "", value, relaxedVersionField); return; }
  if (Array.isArray(value)) { value.forEach((child, index) => assertEvidenceSafe(child, `${path}[${index}]`, relaxedVersionField)); return; }
  if (typeof value === "object") {
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      const normalized = normalizeKey(key);
      const childPath = `${path}.${key}`;
      if (FORBIDDEN_EXACT_KEYS.has(normalized)) throw new EvidenceViolation(childPath, "forbidden key");
      if (FORBIDDEN_KEY_FRAGMENTS.some((fragment) => normalized.includes(fragment))) throw new EvidenceViolation(childPath, "forbidden key");
      assertEvidenceSafe(child, childPath, relaxedVersionField || (path === "$" && key === "environment"));
    }
    return;
  }
  throw new EvidenceViolation(path, `unsupported value type ${typeof value}`);
}
